### ISSUE TITLE
Will there be 國農拉風 support?

### ISSUE THREAD

**Issue by harryoooooooooo** [hhhhhojeihsu/gidis#2]
Hi there,

As title, 拉阿布 channel just uploaded the new video [國農拉風](https://youtu.be/8riDDdgM9pg) recently. Is there any plan to support it?

Cheers!

**Comment by hhhhhojeihsu** [comment]
Thanks for the reminder. I will update it in a few days.

**Comment by hhhhhojeihsu** [comment]
Added in 8b61fbb0f0e035d1f84c601a0a4d5fd8e8a52a33
